### ISSUE TITLE
[Task Tracker]: Mana Calculator

### ISSUE THREAD

**Issue by Dr-Electron** [iotaledger/iota-wiki#1110]
**Is your feature request related to a problem? Please describe.**

Create a mana calculator to calculate mana rewards and granted throughput with the code provided by research

### Task Tracker

```[tasklist]
### Tasks
- [ ] https://github.com/iotaledger/iota-wiki/issues/1267
- [ ] https://github.com/iotaledger/iota-wiki/issues/1268
- [ ] https://github.com/iotaledger/iota-wiki/issues/1282
- [ ] https://github.com/iotaledger/iota-wiki/issues/1269
- [ ] https://github.com/iotaledger/iota-wiki/issues/1270
- [ ] https://github.com/iotaledger/iota-wiki/issues/1271
- [ ] https://github.com/iotaledger/iota-wiki/issues/1277
- [ ] https://github.com/iotaledger/iota-wiki/issues/1272
- [ ] https://github.com/iotaledger/iota-wiki/issues/1273
- [ ] https://github.com/iotaledger/iota-wiki/issues/1274
- [ ] https://github.com/iotaledger/iota-wiki/issues/1275
- [ ] https://github.com/iotaledger/iota-wiki/issues/1276
```

**Comment by luca-moser** [comment]
Ask Olivia to review the PR with a deploy of the mana calculator (somewhere on any page)

**Comment by luca-moser** [comment]
- Did not get any feedback from research yet (Olivia) no response yet
- Collect requirements for the mana calculator by asking the usability task force and incorporate those
- People can check it out using the previews on the PRs
