### ISSUE TITLE
Add How-Tos to ISC docs

### ISSUE THREAD

**Issue by luca-moser** [iotaledger/iota-wiki#1155]
Following is a list of how-tos which should be added under the `Build` section for ISC. The how-tos should use the IOTA SDK to provide code examples for the different operations.

Note that with `ISC account address` with mean the Layer 1 address which is mapped into the ISC chain, therefore the Layer 1 address' reflection on the ISC chain.

```[tasklist]
### Tasks
- [ ] Deposit and withdraw base token to/from ISC account address
- [ ] Deposit and withdraw base token to/from EVM address
- [ ] Deposit and withdraw native asset to/from ISC account address
- [ ] Deposit and withdraw native asset to/from  EVM address
- [ ] Deposit and withdraw NFT to/from ISC account address
- [ ] Deposit and withdraw NFT to/from EVM address
```

**Comment by anistark** [comment]
Working on a [draft](https://hackmd.io/@anistark/rJpw0u-Jp) here.

**Comment by lucas-tortora** [comment]
Missing rust and python examples.

**Comment by lucas-tortora** [comment]
closed in favour of https://github.com/iotaledger/devx/issues/240
