### ISSUE TITLE
Cleanup root

### ISSUE THREAD

**Issue by Dr-Electron** [iotaledger/iota-wiki#1544]
**Is your feature request related to a problem? Please describe.**

With the upcoming changes we should cleanup the wikis root so that it is easier for us and others to make needed changes

**Describe the solution you'd like**

```[tasklist]
### Tasks
- [x] Move `plugins` into `src` folder
- [x] Get rid of `theme` and move components to `src` folder
- [ ] Get rid of `tutorials`, move content to docs and configure tutorial cards in a separate config file
- [ ] Rename `common` folder to `config` and move all relevant configs there
```

**Comment by Dr-Electron** [comment]
If needed we should create sub folders for things like argo and so on.
Also the svgo config can probably removed. (@jlvandenhout said, that docusaurus might use similar parameters as they use svgo internally too)

**Comment by jlvandenhout** [comment]
I converted the related PRs to draft, because we decided to target the main branch for now instead of the v3 upgrade. I'll rebase the PRs on main and resolve any remaining issues.

**Comment by lucas-tortora** [comment]
completed
