### ISSUE TITLE
Remove CLI

### ISSUE THREAD

**Issue by Dr-Electron** [iotaledger/iota-wiki#1546]
With the CLI not really needed anymore we should remove it.

This includes:

```[tasklist]
### Tasks
- [ ] Removing the Wiki cli
- [ ] Create action if needed to replace cli functionality in (other) repo(s)
- [ ] Make sure all cli functionality is now integrated into wiki package
```

**Comment by lucas-tortora** [comment]
No longer necessary
